server:
  port: 8081

spring:
  application:
    name: damai-program
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/damai_program?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      max-active: 50
      min-idle: 20
      initial-size: 20
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        allow: ""
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

damai:
  seat:
    strategy: redis  # redis(V3) 或 database(V2)

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
